services:
  backend-app:
    build: 
      context: ..
      dockerfile: ./docker/backend.dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db-app
    networks:
      - app-network
  frontend-app:
    build:
      context: ..
      dockerfile: ./docker/frontend.dockerfile
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - app-network
  db-app:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=group-purchase-kata
    networks:
      - app-network
  adminer-app:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db-app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge