services:
  backend-app:
    build: 
      context: ..
      dockerfile: ./docker/backend.dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network
  frontend-app:
    build:
      context: ..
      dockerfile: ./docker/frontend.dockerfile
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge