services:
  backend-app:
    build: 
      context: ..
      dockerfile: ./docker/backend.dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge